# Site settings
title: Perry Johnston | Portfolio Website 
email: johnstonperry12345@gmail.com
description: Portfolio website for Perry Johnston featuring projects, technical skills, expereince, and additional personal information.


baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
